# Generated by Django 6.0 on 2025-12-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_assigned_employee_job_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
    ]
