# Generated by Django 6.0 on 2025-12-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
