# Generated by Django 6.0 on 2025-12-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
